In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv('pfm_train.csv')
test_df = pd.read_csv('pfm_test.csv')

In [3]:
train_df.head(5)
y_train = train_df.Attrition
train_df.drop(['Attrition'],axis=1,inplace=True)

In [4]:
def cleaningdata(data):
    data.drop(['Over18'],axis=1,inplace = True)
    data.drop(['StandardHours'],axis=1,inplace = True)
    data.drop(['EmployeeNumber'],axis=1,inplace = True)
    data = pd.get_dummies(data)
    return data

In [5]:
train_df = cleaningdata(train_df)
test_df = cleaningdata(test_df)

In [6]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(train_df, y_train, test_size=0.2)

In [6]:
from sklearn import ensemble
m3 = ensemble.ExtraTreesClassifier(n_estimators=40, 
                                   max_depth=20,
                                   min_samples_split=3,
                                   random_state=0)
m3.fit(train_df, y_train)
y_pred3 = m3.predict(test_df)
sub = pd.DataFrame()
sub['result1'] = y_pred3
# print('Accuracy: {}'.format(m3.score(X_test,y_test)))

In [14]:
pd.DataFrame({'importance':m3.feature_importances_, 'label':train_df.columns.values},
             columns=['importance','label']).sort_values(by='importance',ascending=False)

    importance                              label
46    0.050562                        OverTime_No
0     0.042134                                Age
47    0.040282                       OverTime_Yes
13    0.040192                  TotalWorkingYears
3     0.039618            EnvironmentSatisfaction
7     0.036790                      MonthlyIncome
6     0.036257                    JobSatisfaction
1     0.031685                   DistanceFromHome
11    0.030982           RelationshipSatisfaction
16    0.030251                     YearsAtCompany
4     0.029353                     JobInvolvement
45    0.028963               MaritalStatus_Single
17    0.028881                 YearsInCurrentRole
5     0.028579                           JobLevel
15    0.028082                    WorkLifeBalance
9     0.027452                  PercentSalaryHike
12    0.027156                   StockOptionLevel
2     0.027039                          Education
18    0.026460            YearsSinceLastPromotion
19    0.025501               YearsWithCurrManager
8     0.025113                 NumCompaniesWorked
14    0.022525              TrainingTimesLastYear
29    0.020271             EducationField_Medical
32    0.017811                      Gender_Female
21    0.017655   BusinessTravel_Travel_Frequently
27    0.017518       EducationField_Life Sciences
33    0.016529                        Gender_Male
31    0.015717    EducationField_Technical Degree
10    0.015040                  PerformanceRating
36    0.014752      JobRole_Laboratory Technician
43    0.013791             MaritalStatus_Divorced
22    0.013451       BusinessTravel_Travel_Rarely
44    0.013410              MaritalStatus_Married
42    0.012849       JobRole_Sales Representative
24    0.012306  Department_Research & Development
41    0.011848            JobRole_Sales Executive
40    0.011160         JobRole_Research Scientist
25    0.010498                   Department_Sales
28    0.010406           EducationField_Marketing
38    0.009715     JobRole_Manufacturing Director
34    0.008274  JobRole_Healthcare Representative
30    0.006973               EducationField_Other
20    0.006375          BusinessTravel_Non-Travel
26    0.004893     EducationField_Human Resources
35    0.004405            JobRole_Human Resources
37    0.003884                    JobRole_Manager
23    0.003417         Department_Human Resources
39    0.003198          JobRole_Research Director

In [8]:
from sklearn import ensemble
m4 = ensemble.RandomForestClassifier(n_estimators=100, 
                                   max_depth=22,
                                   min_samples_split=3,
                                   random_state=0)
m4.fit(train_df, y_train)
y_pred4 = m4.predict(test_df)

sub['result2'] = y_pred4

# print('Accuracy: {}'.format(m4.score(X_test,y_test)))

In [9]:
%%time
from lightgbm import LGBMClassifier
m1 = LGBMClassifier(class_weight='balanced', boosting_type='dart',
                         drop_rate=0.1, min_data_in_leaf=50, 
                         max_bin=255,
                         n_estimators=800,
                         bagging_fraction=0.01,
                         min_sum_hessian_in_leaf=1,
                         importance_type='gain',
                         learning_rate=0.2, 
                         max_depth=10, 
                         num_leaves=10)
m1.fit(train_df, y_train)
y_pred1 = m1.predict(test_df)
sub['result3'] = y_pred1

# print('Accuracy: {}'.format(m1.score(X_test,y_test)))

Wall time: 561 ms

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [10]:
preds = sub.mode(axis=1)

In [11]:
sub = pd.DataFrame(columns=['result'])

In [12]:
sub['result'] = preds[0]
sub.to_csv('3ensemble_output.csv',index=None)